In [32]:

from tensorflow.keras.preprocessing.text import one_hot


In [33]:
### sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos .are good' ,]



In [34]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos .are good']

In [35]:
## define the vocbulary size

voc_size = 10000

In [36]:
## one hot representation
one_hot_repr= [one_hot(words,voc_size)for words in sent]

In [37]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
import numpy as np
import pandas as pd


In [39]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4575 9934 3430 1153]
 [   0    0    0    0 4575 9934 3430 7116]
 [   0    0    0    0 4575 3505 3430 5234]
 [   0    0    0 8868 4809 3556 4543 8922]
 [   0    0    0 8868 4809 3556 4543 7017]
 [   0    0    0 6818 4575 9745 3430 8167]
 [   0    0    0    0  744 1162 5997 4543]]


In [40]:
## featuree representation
dim = 10

In [41]:
# model = Sequential()
# model.add(Embedding(voc_size,dim,input_length=sent_length))
# model.compile(optimizer='adam', loss='mse')
# model.summary()


In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential()

model.add(Input(shape=(sent_length,)))
model.add(Embedding(voc_size, dim))

model.compile(optimizer='adam', loss='mse')

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[-1.84247643e-03,  1.78941227e-02,  2.09804438e-02,
         -1.11624375e-02,  2.59141959e-02, -2.60593742e-03,
          3.47949304e-02,  2.22197510e-02,  3.05187218e-02,
         -8.43030214e-03],
        [-1.84247643e-03,  1.78941227e-02,  2.09804438e-02,
         -1.11624375e-02,  2.59141959e-02, -2.60593742e-03,
          3.47949304e-02,  2.22197510e-02,  3.05187218e-02,
         -8.43030214e-03],
        [-1.84247643e-03,  1.78941227e-02,  2.09804438e-02,
         -1.11624375e-02,  2.59141959e-02, -2.60593742e-03,
          3.47949304e-02,  2.22197510e-02,  3.05187218e-02,
         -8.43030214e-03],
        [-1.84247643e-03,  1.78941227e-02,  2.09804438e-02,
         -1.11624375e-02,  2.59141959e-02, -2.60593742e-03,
          3.47949304e-02,  2.22197510e-02,  3.05187218e-02,
         -8.43030214e-03],
        [ 1.98155530e-02, -2.64681708e-02, -4.23648618e-02,
          1.43940374e-03,  6.71520829e-05,  4.87931110e-02,
         -1.55063756e-02,  6.28204271e-03, -4.501788